sonar.projectKey=devsecops-portal
sonar.projectName=DevSecOps Portal
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/.next/**,**/__pycache__/**,**/*.pyc
sonar.python.version=3.12
sonar.typescript.tsconfigPath=frontend/tsconfig.json
sonar.sourceEncoding=UTF-8
